# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xkeyboard-config
Summary:    Alternative xkb data files
Version:    1.8
Release:    1
Group:      System/X11
License:    MIT
BuildArch:  noarch
URL:        http://www.x.org
Source0:    http://xlibs.freedesktop.org/xkbdesc/%{name}-%{version}.tar.bz2
Source100:  xkeyboard-config.yaml
Patch0:     fix-rx51-enter.patch
Patch1:     n950-support.patch
Patch2:     n950-makefile.in-manual-fix.patch
BuildRequires:  pkgconfig(xorg-macros)
BuildRequires:  pkgconfig
BuildRequires:  xkbcomp
BuildRequires:  perl(XML::Parser)
BuildRequires:  gettext
BuildRequires:  intltool
BuildRequires:  fdupes
Provides:   xkbdata
Obsoletes:   xorg-x11-xkbdata


%description
Alternative xkb data files.



%prep
%setup -q -n %{name}-%{version}

# fix-rx51-enter.patch
%patch0 -p1
# n950-support.patch
%patch1 -p1
# n950-makefile.in-manual-fix.patch
%patch2 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --enable-compat-rules \
    --with-xkb-base=%{_datadir}/X11/xkb \
    --disable-xkbcomp-symlink \
    --with-xkb-rules-symlink=xorg

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre

# << install pre
%make_install

# >> install post
# Remove unnecessary symlink
rm -f $RPM_BUILD_ROOT%{_datadir}/X11/xkb/compiled

# Bernie: remove locale stuff
rm -rf $RPM_BUILD_ROOT%{_datadir}/locale

# Create filelist
{
FILESLIST=${PWD}/files.list
pushd $RPM_BUILD_ROOT
find ./usr/share/X11 -type d | sed -e "s/^\./%dir /g" > $FILESLIST
find ./usr/share/X11 -type f | sed -e "s/^\.//g" >> $FILESLIST
popd
}


# << install post
%fdupes  %{buildroot}//usr/share/X11






%files -f files.list
%defattr(-,root,root,-)
# >> files
%{_datadir}/X11/xkb/rules/xorg
%{_datadir}/X11/xkb/rules/xorg.lst
%{_datadir}/X11/xkb/rules/xorg.xml
# << files


