Name: xkeyboard-config
Summary: Alternative xkb data files
Version: 2.5.1
Release: 1
Group: System/X11
License: MIT
URL: http://www.freedesktop.org/wiki/Software/XKeyboardConfig#Releases
Sources:
    - http://xorg.freedesktop.org/archive/individual/data/%{name}-%{version}.tar.bz2
Description: Alternative xkb data files.

PkgConfigBR:
    - xorg-macros
PkgBR:
    - pkgconfig
    - xkbcomp
    - perl(XML::Parser)
    - gettext
    - intltool
Provides:
    - xkbdata
Obsoletes:
    - xorg-x11-xkbdata
ConfigOptions:
    - --enable-compat-rules
    - --with-xkb-base=%{_datadir}/X11/xkb
    - --disable-xkbcomp-symlink
    - --with-xkb-rules-symlink=xorg
    - --disable-runtime-deps
Patches:
    - fix-rx51-enter.patch
    - n950-support.patch
    - n950-makefile.in-manual-fix.patch
    - n810-support.patch
BuildArch: noarch
NoAutoLocale: True
FilesInput: files.list
RunFdupes: 
    - /usr/share/X11

SubPackages:
    - Name: devel
      Group: System/X11
      Summary: Devel package for alternative xkb data files
      Description: Development files for %{name}.
